CREATE DATABASE online_store;
GO;
USE DATABASE online_store;
GO;
CREATE TABLE pictures_products (id INT IDENTITY(1,1), product_id INT, picture_id INT);
GO;
CREATE TABLE pictures (id INT IDENTITY(1,1), picture_key VARCHAR(255));
GO;
CREATE TABLE categories (id INT IDENTITY(1,1), name VARCHAR(255));
GO;
CREATE TABLE products_categories (id INT IDENTITY(1,1), product_id INT, category_id INT);
GO;
CREATE TABLE products (id INT IDENTITY(1,1), name VARCHAR(255), count INT, rating INT, price INT, description VARCHAR(255));
GO;
CREATE TABLE activity_history (id INT IDENTITY(1,1), user_id INT, product_id INT, time_stamp DATETIME, activity VARCHAR(255), notes VARCHAR(1000));
GO;
CREATE TABLE users (id INT IDENTITY(1,1), first_name VARCHAR(255), last_name VARCHAR(255), user_name VARCHAR(255), password VARCHAR(255), admin_privileges BIT);
GO;
CREATE TABLE profiles (id INT IDENTITY(1,1), customer_id INT, street VARCHAR(255), city VARCHAR(255), state VARCHAR(255), phone_number VARCHAR(255));
GO;
CREATE TABLE
